# 교차검증

In [2]:
# 테스트 세트를 사용하지 않고 모델이 과적합인지 과소적합인지 즉 과적합을 판단방법
# 보고서용....... 데이터가 작거나... 또는 머신러닝을 수행을때 과적합이 발생하면...
# 먼저 교차검증으로 평균치를 보여주고 평균 이정도 성능을 보인다.... 명시한다음에..
# 파라메터 튜닝을 통해.. 좀더 수치를 끌어올려본다..
# 그래도 너무  성능이 안좋다....... 데이터를 의심해보자... 잘못수집되었거나. 
# 전처리도 ...... 
# 컬럼이 많다면.... 결정트리의 피처중요도를 이용해서 상위 몇개의 피처만 가지고 다시 수행.

In [4]:
import pandas as pd
df = pd.read_csv("https://raw.githubusercontent.com/bigdataleeky/python/main/wine.csv")
df.head()

alcohol  sugar    pH  class
0      9.4    1.9  3.51    0.0
1      9.8    2.6  3.20    0.0
2      9.8    2.3  3.26    0.0
3      9.8    1.9  3.16    0.0
4      9.4    1.9  3.51    0.0

In [5]:
x = df.iloc[:,:-1]
x.head()

alcohol  sugar    pH
0      9.4    1.9  3.51
1      9.8    2.6  3.20
2      9.8    2.3  3.26
3      9.8    1.9  3.16
4      9.4    1.9  3.51

In [8]:
y = df.iloc[:,-1]
y = y.astype(int)
y.value_counts()

1    4898
0    1599
Name: class, dtype: int64

In [11]:
# 최종테스트 데이터
from sklearn.model_selection import train_test_split
x_train,x_target,y_train,y_target = train_test_split(x,y,test_size=0.2,random_state=42)
x_train.shape, y_train.shape

((5197, 3), (5197,))

In [10]:
# 훈련용데이터를 - 훈련용 + 검증용  8:2
x_train2,x_target2,y_train2,y_target2 =  train_test_split(x_train,y_train,test_size=0.2,random_state=42)

In [12]:
x_train2.shape, y_train2.shape

((4157, 3), (4157,))

In [13]:
from sklearn.tree import DecisionTreeClassifier
dc =  DecisionTreeClassifier(random_state=42)
dc.fit(x_train2, y_train2)
dc.score(x_train2, y_train2), dc.score(x_target2, y_target2)

(0.9971133028626413, 0.864423076923077)

In [14]:
# GridSearchCV --- > 하이퍼 파라메터 튜닝....  model_selection
from sklearn.model_selection import cross_validate
score =  cross_validate(dc,x_train, y_train)


{'fit_time': array([0.00698042, 0.00698304, 0.0069809 , 0.00600886, 0.0059824 ]),
 'score_time': array([0.0009973 , 0.00199366, 0.00199485, 0.0010016 , 0.00099802]),
 'test_score': array([0.86923077, 0.84615385, 0.87680462, 0.84889317, 0.83541867])}

In [17]:
score['test_score']

array([0.86923077, 0.84615385, 0.87680462, 0.84889317, 0.83541867])

In [18]:
score['test_score'].mean()

0.855300214703487

In [20]:
import numpy as np
np.mean(score['test_score'])

0.855300214703487

# 교차검증의 장점
## 모든데이터 셋을 훈련과 평가에 활용
## 정확도를 향상
## 데이터가 부족할때 이로인한 과적합
## 데이터 편중을 막을수 있다
## 좀더 일반화된 모델을

# 단점
## 시간이 과다하게 소요된다.

In [24]:
# Kfold 방식되 거의 유사 
# 분류기를 통한 교차검증
# 분류모델이면 StratifiedKFold 사용하고 그 외에는 
# 예측..군집일경우에는 KFold
from sklearn.model_selection import StratifiedKFold
score =  cross_validate(dc,x_train, y_train, cv=StratifiedKFold() )
score['test_score'].mean()

0.855300214703487

In [27]:
dc.feature_names_in_, dc.feature_importances_

(array(['alcohol', 'sugar', 'pH'], dtype=object),
 array([0.23614177, 0.50084785, 0.26301038]))

In [33]:
dc.feature_importances_

array([0.23614177, 0.50084785, 0.26301038])

In [35]:
np.sort(dc.feature_importances_)[::-1]

array([0.50084785, 0.26301038, 0.23614177])

In [36]:
# 결정트리의 사용 이유 : 정확한 분류..
# 부가적인 기능 : 피어의 중요도를 알수 있다..
# 만약에 피처가 너무 많다면.... feature_importances_의 값을 내람차순으로 정렬한후 상위 몇개의 feature만 추출해서
# 원하는 머신러닝에 적용

In [41]:
# 교차검증으로 과적합을 피할수 있다면..... 성능을 높이기 위해서 하이퍼 파라메터 튜닝을통해 성능 확인
dc.get_params()

{'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'random_state': 42,
 'splitter': 'best'}

In [46]:
p ={
    'min_impurity_decrease':[0.0001,0.001,0.01,0.1,1,10,100]
}

In [47]:
from sklearn.model_selection import GridSearchCV

In [50]:
gs = GridSearchCV(dc, param_grid=p)

In [51]:
gs.fit(x_train,y_train)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42),
             param_grid={'min_impurity_decrease': [0.0001, 0.001, 0.01, 0.1, 1,
                                                   10, 100]})

In [53]:
gs.best_params_

{'min_impurity_decrease': 0.0001}

In [54]:
model = gs.best_estimator_

In [66]:
model.score(x_target,y_target)

0.8653846153846154

In [67]:
model.score(x_train, y_train), model.score(x_target, y_target)

(0.9615162593804117, 0.8653846153846154)

In [74]:
params = {
    'min_impurity_decrease':[0.0001,0.001,0.01,0.1,1,10,100],
    'max_depth' : [3,5]
}

In [75]:
gs = GridSearchCV(dc, param_grid=params)
gs.fit(x_train,y_train)
gs.best_params_

{'max_depth': 5, 'min_impurity_decrease': 0.001}

In [76]:
model = gs.best_estimator_
model.score(x_train, y_train), model.score(x_target, y_target)

(0.8664614200500289, 0.8615384615384616)

In [77]:
# 앙상블 학습알고리즘 : 정형데이터를 다루는데 성능이 가장 뛰어난(머신러닝..), 성능을 높이기 위해 여러개의 
# 모델을 사용
# 랜덤포레스트 알고리즘, 엑스트라 트리알고리즘ㅡ 그레이디언트 부스팅 알고리즘

# 랜덤포레스트 알고리즘  : 결정트리를 랜덤하게 만들어서 숲을 구성
# 랜덤하게 데이터를 추출하는 방법 : 부트스트랩 샘플

In [81]:
# 트리알고리즘은 정규화 안한다...... (StandardScaling) ...
df = pd.read_csv("https://raw.githubusercontent.com/bigdataleeky/python/main/wine.csv")
df['class'] = df['class'].astype(int)
df.head()

alcohol  sugar    pH  class
0      9.4    1.9  3.51      0
1      9.8    2.6  3.20      0
2      9.8    2.3  3.26      0
3      9.8    1.9  3.16      0
4      9.4    1.9  3.51      0

In [83]:
x =df.iloc[:,:-1]
y =df.iloc[:,-1]
x.shape, y.shape

((6497, 3), (6497,))

In [84]:
from sklearn.ensemble import RandomForestClassifier

In [87]:
x_train,x_target,y_train,y_target =  train_test_split(x,y,random_state=42)
x_train.shape,y_train.shape

((4872, 3), (4872,))

In [96]:
rfc = RandomForestClassifier(random_state=42)
rfc.fit(x_train, y_train)
rfc.score(x_train, y_train), rfc.score(x_target, y_target) 

(0.9973316912972086, 0.8812307692307693)

In [97]:
score =  cross_validate(rfc,x_train,y_train,cv=StratifiedKFold() )
score

{'fit_time': array([0.23491669, 0.22261548, 0.22533751, 0.23141098, 0.23322868]),
 'score_time': array([0.01994824, 0.02077603, 0.02100277, 0.01994729, 0.02043676]),
 'test_score': array([0.88      , 0.90051282, 0.90349076, 0.89014374, 0.88295688])}

In [98]:
score['test_score'].mean()

0.8914208392565683

In [99]:
# 리포트
# 피처의 중요도를 알수....
# 랜덤포레스트를 사용하는데. 크로스벨리데이터를 이용해서 전체학습데이터를 사용했다.
# 피처의 중요도를 알아보기위해
rfc.fit(x_train,y_train)
rfc.feature_importances_

array([0.23155241, 0.49706658, 0.27138101])

In [100]:
# Tree 그 자체로 뭔가 구분도 할수도 있지만... Feature 엔지니어링에 활용

In [101]:
rfc2 = RandomForestClassifier(oob_score=True,random_state=42)
rfc2.fit(x_train,y_train)
rfc2.feature_importances_

array([0.23155241, 0.49706658, 0.27138101])

In [ ]:
# ....